In [2]:
import sys, os
from matplotlib import pyplot as plt
from pprint import pprint
import numpy as np

filein = "../Benchmark/test0.out"
data = np.loadtxt(filein,skiprows=1)
eig_vals = np.linalg.eigvals(data)
eig_vals_sorted = np.sort(eig_vals)
pprint(eig_vals_sorted)

array([   3.00192468,    6.87778562,   10.66589402,   14.34670334,
         17.9350893 ,   21.40394978,   24.76412352,   27.99547052,
         31.09086473,   34.03956546,   36.82716349,   39.41893798,
         41.77369887,   43.89474582,   45.93278129,   48.19407077,
         50.76574958,   53.61020972,   56.68880345,   60.00934659,
         63.51783591,   67.22892588,   71.15368648,   75.25855653,
         79.58095501,   84.06523308,   88.76328669,   93.66490392,
         98.66595167,  103.84802978,  109.36371687,  114.84243018,
        120.74738465,  126.73042986,  132.74578703,  139.21690509,
        145.68270982,  152.56897078,  159.53693989,  166.61297974,
        173.90935316,  181.26988915,  188.97306186,  196.89516319,
        204.89015423,  212.89641467,  221.48693418,  230.71771826,
        241.96853287,  256.46028105])


In [2]:
import sys,os
import numpy as np
from pprint import pprint

filein = "../Benchmark/test2_4.in"
mtx = np.loadtxt(filein)
print(np.matrix(mtx))
w,v = np.linalg.eig(mtx)
w,v

[[ 1.  1.  0.  3.]
 [ 1.  1.  0.  1.]
 [ 0.  0.  1.  0.]
 [ 3.  1.  0.  0.]]


(array([ 4.16866865, -2.54560771,  0.37693905,  1.        ]),
 array([[-0.69250684, -0.63953134,  0.33381723,  0.        ],
        [-0.40660982, -0.03620833, -0.91288412,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ],
        [-0.59590496,  0.76791186,  0.23496521,  0.        ]]))

In [21]:
import sys, os
from matplotlib import pyplot as plt
from pprint import pprint
import numpy as np


ffig = "omega1.pdf"
filein = "efnts.out"
data = np.loadtxt(filein)
y = data[:,4]

#n=len(y)
x = np.arange(0.01,1.01,0.01)
plot = plt.plot(x,y)
plt.show()
plt.savefig(ffig)
plt.clf()