In [30]:
import sys, os
from matplotlib import pyplot as plt
from pprint import pprint
import numpy as np
import time

filein = "../Benchmark/test0.out"
data = np.loadtxt(filein,skiprows=1)
t0=time.clock()
eig_vals = np.linalg.eigvals(data)
print time.clock() - t0, "seconds process time"
eig_vals_sorted = np.sort(eig_vals)
pprint(eig_vals_sorted)

0.0267866036183 seconds process time
array([    2.97387033,     6.98289844,    10.99475637,    14.98379383,
          19.01167273,    23.31198994,    28.15944706,    33.76587707,
          40.14443852,    47.27265215,    55.16690311,    63.8423081 ,
          73.26887792,    83.35842356,    94.16739195,   105.72608972,
         117.91859699,   130.73489005,   144.28783816,   158.47130723,
         173.28298399,   188.73994031,   204.68639703,   221.33444678,
         238.47179394,   256.25511466,   274.46205197,   293.2727144 ,
         312.54295342,   332.32961   ,   352.48908517,   373.16193691,
         394.29643001,   415.70931559,   437.61019429,   459.85894321,
         482.35571933,   505.25540083,   528.43087533,   551.87145813,
         575.56493486,   599.45005521,   623.57754422,   647.87040587,
         672.33824185,   696.93014597,   721.57560553,   746.36871258,
         771.17967712,   796.06022293,   820.91024952,   845.80863733,
         870.61472056,   895.42895551,  

In [2]:
import sys,os
import numpy as np
from pprint import pprint

filein = "../Benchmark/test2_4.in"
mtx = np.loadtxt(filein)
print(np.matrix(mtx))
w,v = np.linalg.eig(mtx)
w,v

[[ 1.  1.  0.  3.]
 [ 1.  1.  0.  1.]
 [ 0.  0.  1.  0.]
 [ 3.  1.  0.  0.]]


(array([ 4.16866865, -2.54560771,  0.37693905,  1.        ]),
 array([[-0.69250684, -0.63953134,  0.33381723,  0.        ],
        [-0.40660982, -0.03620833, -0.91288412,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ],
        [-0.59590496,  0.76791186,  0.23496521,  0.        ]]))

In [21]:
import sys, os
from matplotlib import pyplot as plt
from pprint import pprint
import numpy as np


ffig = "omega1.pdf"
filein = "efnts.out"
data = np.loadtxt(filein)
y = data[:,4]

#n=len(y)
x = np.arange(0.01,1.01,0.01)
plot = plt.plot(x,y)
plt.show()
plt.savefig(ffig)
plt.clf()

In [25]:
########################################
## Plot number of iterations vs.      ##
## number of grid points (matrix dim) ##
########################################
import sys, os, math
from matplotlib import pyplot as plt
import numpy as np

x=[20,50,100,200,500]
##xl=[math.log10(t) for t in x]
y=[609,4047,16532,66618,421903]
f=np.polyfit(x,y,2)
ff=np.poly1d(f)
xf=np.linspace(10,550)
print(np.poly1d(f))
##yl=[math.log10(t) for t in y]
##plt.axis([0,5,0,7])
##plot = plt.plot(x,y,'b+',markersize=10)
##plt.show()
fig1, ax1=plt.subplots()
ax1.plot(x,y,'r+',markersize=10)
ax1.plot(xf,ff(xf),'b')
plt.xlabel('Dimensionality')
plt.ylabel('Number of Iterations')
ax1.set_xscale('log')
ax1.set_yscale('log')
plt.show()
#plt.savefig("dnit.pdf")
#plt.clf()

       2
1.705 x - 9.114 x + 299.2


In [40]:
#####################################
## Plot first three wave functions ##
#####################################
import sys, os, math
from matplotlib import pyplot as plt
import numpy as np

x = np.linspace(0.1,5.1,50)

infile1 = "../Benchmark/wavefunction0.out"
infile2 = "../Benchmark/wavefunction1.out"
infile3 = "../Benchmark/wavefunction2.out"

y1 = np.loadtxt(infile1)
y2 = np.loadtxt(infile2)
y3 = np.loadtxt(infile3)

plt.axis([0.,5.,0.,0.1])
plot1 = plt.plot(x,y1,'b',label='gs')
plot2 = plt.plot(x,y2,'r',label='ex1')
plot3 = plt.plot(x,y3,'g',label='ex2')
plt.xlabel(r'$\rho$')
plt.ylabel(r'$|\psi|^2$')
plt.legend(loc=1)
plt.show()